[package]
name = "data-collector"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
franz-client = "0.1.2"
log = "0.4.22"
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
twitcheventsub = "0.1.4"
