name: MostlyBot Test PR

on:
  pull_request:
    branches: [ "main" ]
    paths: [ "twitch/bot/**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cd twitch/bot && cargo build --verbose
    - name: Run tests
      run: cd twitch/bot && cargo test --verbose
